local SI = {}

-------- --------------------------------------------------------------------
-- Each SI you create you need to register with it with ESO like below
-----------------------------------------------------------------------------
SI.TELEWELCOMEMSG = "SI_TELE_WELCOMEMSG"
SI.TELEREFRESH = "SI_TELE_REFRESH"
SI.TELEPARTYUP = "SI_TELE_PARTY_UP"
SI.TELELOCATION = "SI_TELE_LOCATION"
SI.TELEPLAYERLOCATION = "SI_TELE_PLAYER_LOCATION"
SI.TELEINVITE = "SI_TELE_INVITES"
SI.TELETELEPORT = "SI_TELE_TELEPORT"
SI.TELECLOSE = "SI_TELE_CLOSE"

SI.TELE_UNABLE_TO_PORTAL = "SI_TELE_UNABLE_TO_PORTAL"
SI.TELE_TO_PLAYER = "SI_TELE_TO_PLAYER"
SI.TELE_PLAYER = "SI_TELE_PLAYER"

SI.TELE_ZONE = "SI_TELE_ZONE"
SI.TELE_FAST = "SI_TELE_FAST"
SI.TELE_TELE = "SI_TELE_TELE"


SI.TELE_FREQUENCY = "SI_TELE_FREQ"
SI.TELE_PORT_IN_SEC = "SI_TELE_PORT_IN_SEC"

SI.TELE_PUT_ON_FULL_SET_EXPLOATION_GEAR = "SI_TELE_PUT_ON_FULL_SET_EXPLOATION_GEAR"
SI.TELE_SET_PORTAL_FREQ = "SI_TELE_SET_PORT_FREQ"
SI.TELE_SET_PORTAL_FREQ_INFO = "SI_TELE_SET_PORT_FREQ_INFO"
SI.TELE_PORTAL_DISABLED = "SI_TELE_PORTAL_DISABLED"
SI.TELE_PORTAL_ENABLED = "SI_TELE_PORTAL_ENABLED"
SI.TELE_ERROR = "SI_TELE_ERROR"
SI.TELE_AGAIN_DISABLE = "SI_AUTO_TELE_TELEPORTAL"
SI.TELE_IN_FIVE_SEC = "SI_TELE_IN_FIVE_SEC"





-- utility functions
function SI.get(key, n)
    assert(key ~= nil)
    return assert(GetString(_G[key], n))
end

Teleporter.SI = SI
