local SI = {}

-- Bait Type
SI.GUTS = "SI_GUTSz"
SI.INSECTS = "SI_INSECTSz"
SI.WORMS = "SI_WORMSz"
SI.MINNOW = "SI_MINNOWz"
SI.FISHROE = "SI_FISHROEz"
SI.CHUB = "SI_CHUBz"
SI.CRAWLERS = "SI_CRAWLERSz"
SI.SHAD = "SI_SHADz"

SI.FISHINGHOLE = "SI_FISHINGHOLEz"

SI.AREUSEDIN = "SI_AREUSEDINz"

-- Where

SI.RIVERS = "SI_RIVERSz"
SI.LAKES = "SI_LAKESz"
SI.SEA = "SI_SEAz"
SI.FOULWATER = "SI_FOULWATERz"

-- 
--MESSAGE
SI.GUTSMSG = "SI_GUTSMSG"
SI.INSECTSMSG = "SI_INSECTSMSG"
SI.WORMSMSG = "SI_WORMSMSG"
SI.MINNOWMSG = "SI_MINNOWMSG"
SI.FISHROEMSG = "SI_FISHROEMSG"
SI.CHUBMSG = "SI_CHUBMSG"
SI.CRAWLERSMSG = "SI_CRAWLERSMSG"
SI.SHADMSG = "SI_SHADMSG"

--Misc
SI.MOREBAIT = "SI_MOREBAIT"
SI.REELIN = "SI_REELIN"
SI.SHESABITER = "SI_SHESABITER"

-- OPTIONS MENU
SI.FISHOPTIONS = "SI_FISHOPTIONS"
SI.RECEIVEBAITALERTS = "SI_RECEIVEBAITALERTS"
SI.BAITMSG = "SI_BAITMSG"
SI.RECEIVEREELALERTS = "SI_RECEIVEREELALERTS"
SI.REELMSG = "SI_REELMSG"

SI.ONLYGOOD = "SI_ONLYGOOD"
SI.DONATIONS = "SI_DONATIONS"
SI.BADASS = "SI_BADASS"

--Various App
SI.BETA = "SI_BETAz"
SI.REPORTTHATSHITYO = "SI_REPORTTHATSHITYO"

-- utility functions
function SI.get(key, n)
    assert(key ~= nil)
    return assert(GetString(_G[key], n))
end

FishMe.SI = SI
